# Generated by Django 5.0 on 2025-02-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_remove_recipe_category_recipe_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='category',
            new_name='categories',
        ),
    ]
