# Generated by Django 5.0 on 2025-02-19 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_rename_category_recipe_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='categories',
            new_name='tags',
        ),
    ]
