# Generated by Django 5.0 on 2025-02-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_rename_category_tag_rename_categories_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='isSaved',
            field=models.BooleanField(default=False),
        ),
    ]
