# Generated by Django 5.0 on 2025-02-21 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_recipe_issaved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cooking_time',
            new_name='preparation_time',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe.recipe'),
        ),
    ]
