# Generated by Django 5.0 on 2025-02-22 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_rename_cooking_time_recipe_preparation_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='isSaved',
        ),
        migrations.AddField(
            model_name='recipe',
            name='saved_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='saved_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
