# Generated by Django 5.0 on 2025-02-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_review_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='conversationmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='ConversationMessage',
        ),
    ]
